/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'

const SplatLazyRouteImport = createFileRoute('/$')()
const CodigoQrLazyRouteImport = createFileRoute('/codigo-qr')()
const PrivacyPolicyLazyRouteImport = createFileRoute('/privacy-policy')()
const TermsOfServiceLazyRouteImport = createFileRoute('/terms-of-service')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatLazyRoute = SplatLazyRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/$.lazy').then((d) => d.Route))
const CodigoQrLazyRoute = CodigoQrLazyRouteImport.update({
  id: '/codigo-qr',
  path: '/codigo-qr',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/codigo-qr.lazy').then((d) => d.Route))
const PrivacyPolicyLazyRoute = PrivacyPolicyLazyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/privacy-policy.lazy').then((d) => d.Route),
)
const TermsOfServiceLazyRoute = TermsOfServiceLazyRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/terms-of-service.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatLazyRoute
  '/codigo-qr': typeof CodigoQrLazyRoute
  '/privacy-policy': typeof PrivacyPolicyLazyRoute
  '/terms-of-service': typeof TermsOfServiceLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatLazyRoute
  '/codigo-qr': typeof CodigoQrLazyRoute
  '/privacy-policy': typeof PrivacyPolicyLazyRoute
  '/terms-of-service': typeof TermsOfServiceLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatLazyRoute
  '/codigo-qr': typeof CodigoQrLazyRoute
  '/privacy-policy': typeof PrivacyPolicyLazyRoute
  '/terms-of-service': typeof TermsOfServiceLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/codigo-qr' | '/privacy-policy' | '/terms-of-service'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/codigo-qr' | '/privacy-policy' | '/terms-of-service'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/codigo-qr'
    | '/privacy-policy'
    | '/terms-of-service'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatLazyRoute: typeof SplatLazyRoute
  CodigoQrLazyRoute: typeof CodigoQrLazyRoute
  PrivacyPolicyLazyRoute: typeof PrivacyPolicyLazyRoute
  TermsOfServiceLazyRoute: typeof TermsOfServiceLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codigo-qr': {
      id: '/codigo-qr'
      path: '/codigo-qr'
      fullPath: '/codigo-qr'
      preLoaderRoute: typeof CodigoQrLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatLazyRoute: SplatLazyRoute,
  CodigoQrLazyRoute: CodigoQrLazyRoute,
  PrivacyPolicyLazyRoute: PrivacyPolicyLazyRoute,
  TermsOfServiceLazyRoute: TermsOfServiceLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
